//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public int ID { get; set; }
        public int MaBuoiHoc { get; set; }
        public string MaSV { get; set; }
        public Nullable<int> Trangthai { get; set; }
    
        public virtual BuoiHoc BuoiHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
