//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamDu
    {
        public string MSSV { get; set; }
        public string MaKH { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
